### ISSUE TITLE
Branch Address

### ISSUE THREAD

**Issue by cadeath** [cloudo9/Dalton#159]
Include the branch address at the Pawnticket Header

- [x] 1. Settings has Branch Address
- [ ] 2. Auto Print Branch Ticket

**Comment by marzxxx90** [comment]
Added Branch Address in settings
Update Gui Settings
Branch:Setting Module
Updated from 1.4 POS

**Comment by marzxxx90** [comment]
Update Version to 1.5.0.0

**Comment by cadeath** [comment]
Please change the default as BLANK,
remove the Zero

**Comment by marzxxx90** [comment]
Created Patch for Branch Address

**Comment by cadeath** [comment]
>

**Comment by cadeath** [comment]
> Created Patch for Branch Address
What patch? the system displays 0 value by default, it should be BLANK. this should not be use as patch only

**Comment by marzxxx90** [comment]
Update Function to return Blank instead of 0
