### ISSUE TITLE
User Management Enhancement

### ISSUE THREAD

**Issue by Bladier** [cloudo9/Dalton#165]
User Details
   -Firstname, Lastname, Password, Email Address, Contact Number, etc.
Password Policy
   - The password will expired after 'X' days of usage.
   - If the user cannot login in 'X' days the user account will be expired.
   - Cannot reuse the password.
   - Not reusable 'X' times password expiration (the last 3 password cannot be use except the first password.)
Lock Down
   - If the user enter his/her password 'X' times account will be temporarily inactive. If the account is lock the user will contact the MIS Dept.
Rule Base Privileges ( More complication)
   -Dynamic registry of rule privileges.
   -The value is either No Access, Read Only or Full Access.

**Comment by cadeath** [comment]
Any update?

**Comment by Bladier** [comment]
Password expiration OKEY.
Account Expiration OKEY.
Password trap not reusable OKEY.
Login failed attempt OKEY.
Locked account OKEY.
Rule base privilege functions OKEY. Functions are ready to use.
To do junmar adding privileges.

**Comment by cadeath** [comment]
Provide a DEVELOPER'S GUIDE
