### ISSUE TITLE
Auto Update CIR

### ISSUE THREAD

**Issue by cadeath** [cloudo9/Dalton#175]
This module helps the System Admin to automatically update the branch database for Price, Pawning Items, etc...

This requires Repository and update file

**Comment by Bladier** [comment]
- Auto update cir files, Create Cir folder in DIS for cir files.
- After update, delete all cir in the CIR folder

**Comment by Bladier** [comment]
Changes: Auto update cir files, Create folder CIR files in DIS
updated from v1.6
