### ISSUE TITLE
New GUI

### ISSUE THREAD

**Issue by cadeath** [cloudo9/Dalton#58]
Improve the GUI of the pawnshop system
provide proposed design here, do not merge until approve.
#55

**Comment by Blade1992** [comment]
New Proposed Main Form Design.
Branch Name: New-GUI
For Approval.

**Comment by cadeath** [comment]
Dili ni siya BRANCH

Please provide SCREENSHOTS OR JPEG only
Please ask if you are confuse kay nag.ingon nako na ayaw himua daan

**Comment by Blade1992** [comment]
![mainform_des_ps1](https://cloud.githubusercontent.com/assets/19383719/16440213/46ebb604-3df2-11e6-987a-dbd748b5f2a9.jpg)

Mao ni ang screenshot sir.

**Comment by Blade1992** [comment]
For approval...

**Comment by cadeath** [comment]
Very Good
change it into
DALTON PAWNSHOP AND JEWELRIES, INC. <--- Title
Pawnshop System <--- Sub Title

**Comment by Blade1992** [comment]
DALTON PAWNSHOP AND JEWELRIES, INC mao ni ang ibutang sa pagload sa form sir?

**Comment by cadeath** [comment]
dili mau na imong ibutang sa BANNER

**Comment by Blade1992** [comment]
Okey sir.

**Comment by Blade1992** [comment]
![new_update_mainform_with_title](https://cloud.githubusercontent.com/assets/19383719/16443609/6dcbab66-3e0c-11e6-9006-04fbfe251866.jpg)
Sir ari ang design.

**Comment by cadeath** [comment]
Good,

unaha sa inyo ang Urgents... later na ang GUI pag.Version 2 nato

**Comment by Blade1992** [comment]
OK sir. gina trabaho na namo tong sa Money transfer sir,..
